### ISSUE TITLE
Recording Blocking UI

### ISSUE THREAD

**Issue by navrajkambo** [qiuxiang/react-native-recording#13]
When I run a recording instance on my iPhone, my react-native UI gets blocked. It seems to me that since events are generated on incoming data from the audio codec, and the events are dispatched to the main thread, my react program gets stuck dealing with the recording data, instead of doing other things. 

For instance, when I add the following lines of code `Recording.addRecordingEventListener(datab => this.circularBuff.enqueue(datab));` which esentially adds data to a buffer, I am not able to trigger the `Recording.Stop()` method from my UI with touch input. On android, there is a lag after I try and stop a recording. 

My goal is to be able to detect an impulse from a small amount of buffered data using JS.

**Comment by qiuxiang** [comment]
Do you have an example? This library works fine on my other project [react-native-tuner](https://github.com/qiuxiang/react-native-tuner).

**Comment by navrajkambo** [comment]
I think I may have resolved the issue. Thanks anyways!

**Comment by vynogradskyi** [comment]
> Do you have an example? This library works fine on my other project [react-native-tuner](https://github.com/qiuxiang/react-native-tuner).

Hi, haven't you notice high memory usage on Recording? I see like 2mb per second memory usage raise for Android. I think it is in the part where data is pushed to WritableArray. Do you notice something like that on your proj?
