### ISSUE TITLE
TypeError: null is not an object (evaluating "Recording.init")

### ISSUE THREAD

**Issue by mahdimmr** [qiuxiang/react-native-recording#23]
export default {
  // TODO: params check
  init: (options: {
    bufferSize: number,
    sampleRate: number,
    bitsPerChannel: 8 | 16,
    channelsPerFrame: 1 | 2,
  }) => Recording.init(options),
  start: () => Recording.start(),
  stop: () => Recording.stop(),
  addRecordingEventListener: listener => eventEmitter.addListener('recording', listener)
}

is not working on the 0.62.2
fix this PLEASE

**Comment by aaronshier** [comment]
Same issue here

**Comment by sdakansu** [comment]
Same problem.

**Comment by qiuxiang** [comment]
Fixed in v0.5.1

**Comment by ysvahn** [comment]
Still happening on 0.5.1

**Comment by ysvahn** [comment]
My bad, I was using Expo and it blocks a lot of native customization.

I migrated to a standard RN project and it seems to be working now
