### ISSUE TITLE
stop()之后，如果再次init()，会出现重复录制的情况

### ISSUE THREAD

**Issue by jiyarong** [qiuxiang/react-native-recording#4]
<img width="1228" alt="2017-12-22 4 47 08" src="https://user-images.githubusercontent.com/8100962/34291579-c9deeee2-e737-11e7-9514-0745da0a002d.png">

这是第一次`init`并且`start`之后的数据
但是当我`stop`之后，首先，如果不再次`init`，`start`是无效的，但是我如果再次`init`，会出现这样的情况

<img width="1219" alt="2017-12-22 4 49 38" src="https://user-images.githubusercontent.com/8100962/34291644-22493dee-e738-11e7-8805-4d02f8288d0a.png">

音频被重复记录了，如果反复这样操作，会继续往上叠加，求助

**Comment by jiyarong** [comment]
重复的原因不是init，是`on`这个监听，有没有什么方法能取消这个监听，因为我发现即便组件销毁了，这个监听实际上还在

**Comment by qiuxiang** [comment]
确实有必要加一个取消监听的方法

**Comment by jiyarong** [comment]
多谢，期待下个版本

**Comment by qiuxiang** [comment]
更新了一个版本，接口有变动。现在要这样写：
```javascript
const listener = Recording.addRecordingEventListener(cb)
listener.remove() // 移除监听
```

**Comment by jiyarong** [comment]
好的，多谢了，我现在用redux，然后在`componentWillReceiveProps`里面接，别提有多蛋疼了，有了这个就能解决了！
