### ISSUE TITLE
Callback not firing on iOS

### ISSUE THREAD

**Issue by jankaifer** [qiuxiang/react-native-recording#40]
The same build worked two weeks ago. But when we tested it today it won't fire callbacks on iOS.

Actually, it will fire just once with an empty array.

It happens on multiple versions of iOS (we checked 14.0, 14.5, and 15 beta). (at least 14.0 worked two weeks ago). And I cannot reproduce it in ios emulator.

Are you experiencing similar issues?

**Comment by hieuptit93** [comment]
I also had the same problem. Did you fix it yet?

**Comment by jankaifer** [comment]
Actually, it automatically fixed itself. (iOS update or something?).

But we have already implemented our own native module with newer APIs. We are using this lib only for Android now.
