### ISSUE TITLE
 大佬 这个库还能不能用？怎么只有开始录音，没有结束录音的api

### ISSUE THREAD

**Issue by chenxiong666** [qiuxiang/react-native-recording#7]

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-recording/blob/ffb08ac2c0cf31959e325da520cacb165e5777ef/lib/index.js#L14

**Comment by chenxiong666** [comment]
大佬，录音完获取到的音频能不能转换成路径啊？

**Comment by qiuxiang** [comment]
不能
